config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.petri

  constraints host: config[:user][:host] do
    namespace :user, path: config[:user][:path] do
      root 'top#index'
      resource :session, only: [ :new, :create, :destroy ]
      resources :posts, only: [ :index, :new, :create, :show ] do
        resources :answer, only: [ :create, :edit, :update]
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :content, presence: true
  validates_length_of :content, :maximum => 10000

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :answers, class_name: 'Answer', dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :title, :content, presence: true
  validates_length_of :title, :maximum => 100
  validates_length_of :content, :maximum => 10000
end

app/models/user.rb
class User < ActiveRecord::Base

  before_validation do
    self.email = email
    self.email_for_index = email.downcase if email
  end

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  def active?
    !suspended? && start_date <= Date.today &&
      (end_date.nil? || end_date > Date.today)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :set_layout

  private
  def set_layout
    if params[:controller].match(%r{\A(user)/})
      Regexp.last_match[1]
    else
      'user'
    end
  end
end

app/controllers/user/answer_controller.rb
class User::AnswerController < User::Base
  def create
    @answer = Answer.new(post_params)
    @answer.post_id = params[:post_id]
    @answer.user_id = session[:user_id]
    if @answer.save
      flash.notice = '回答を投稿しました。'
    else
      flash.now.alert = '入力に誤りがあります。'
    end
    @post = Post.find(params[:post_id])
    @answer = Answer.new
    render 'user/posts/show'
  end

  private
  def post_params
    params.require(:answer).permit(
      :content
    )
  end
end

app/controllers/user/base.rb
class User::Base < ApplicationController
  before_action :authorize
  before_action :check_account
  before_action :check_timeout

  private
  def current_user
    if session[:user_id]
      @current_user ||=
        User.find_by(id: session[:user_id])
    end
  end

  helper_method :current_user

  def authorize
    unless current_user
      flash.alert = 'ログインしてください。'
      redirect_to :new_user_session
    end
  end

  def check_account
    if current_user && !current_user.active?
      session.delete(:user_id)
      flash.alert = 'アカウントが無効になりました。'
      redirect_to :user_root
    end
  end

  TIMEOUT = 60.minutes

  def check_timeout
    if current_user
      if session[:last_access_time] >= TIMEOUT.ago
        session[:last_access_time] = Time.current
      else
        session.delete(:user_id)
        flash.alert = 'セッションがタイムアウトしました。'
        redirect_to :new_user_session
      end
    end
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < User::Base
  def index
    @posts = Post.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @answer = Answer.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      flash.notice = '質問を投稿しました。'
      redirect_to :user_posts
    else
      flash.now.alert = '入力に誤りがあります。'
      render action: 'new'
    end
  end

  private
  def post_params
    params.require(:post).permit(
      :title, :content
    )
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < User::Base
  skip_before_action :authorize

  def new
    if current_user
      redirect_to :user_root
    else
      @form = User::LoginForm.new
      render action: 'new'
    end
  end

  def create
    @form = User::LoginForm.new(params[:user_login_form])
    if @form.email.present?
      user = User.find_by(email_for_index: @form.email.downcase)
    end
    if User::Authenticator.new(user).authenticate(@form.password)
      if user.suspended?
        flash.now.alert = 'アカウントが停止されています。'
        render action: 'new'
      else
        session[:user_id] = user.id
        session[:last_access_time] = Time.current
        flash.notice = 'ログインしました。'
        redirect_to :user_root
      end
    else
      flash.now.alert = 'メールアドレスまたはパスワードが正しくありません。'
      render action: 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash.notice = 'ログアウトしました。'
    redirect_to :user_root
  end
end

app/controllers/user/top_controller.rb
class User::TopController < User::Base
  def index
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @@markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML,
    autolink: true,
    space_after_headers: true,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    tables: true,
    hard_wrap: true,
    xhtml: true,
    lax_html_blocks: true,
    strikethrough: true,
    filter_html: true
  def markdown(text)
    @@markdown.render(text).html_safe
  end
end

app/views/layouts/user.html.slim
DOCTYPE
html
  head
    title Petri
    = stylesheet_link_tag    'user', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #wrapper
      == render 'user/shared/header'
      #container
        == yield
      == render 'shared/footer'

app/views/shared/_footer.html.slim
footer
  p PETRI &copy; 2015 Shinse

app/views/user/posts/_answer.html.slim
div
  = f.label :content, '回答'
  = f.text_area :content, :size => "80x10"

app/views/user/posts/_form.html.slim
div
  = f.label :title, 'タイトル'
  = f.text_field :title, size: 80
div
  = f.label :content, '内容'
  = f.text_area :content, :size => "80x10"

app/views/user/posts/index.html.slim
- @title = '質問一覧'
h1 = @title
div
  table.pure-table.pure-table-horizontal
    head
      tr
        th #
        th 回答数
        th タイトル
        th 投稿者
    tbody
      - @posts.each do |p|
        tr
          td = link_to p.id, user_post_path(id: p.id)
          td = p.answers.length
          td = link_to p.title, user_post_path(id: p.id)
          td
            = p.user.family_name
            = p.user.given_name

app/views/user/posts/new.html.slim
- @title = '質問作成'
h1 = @title

.pure-u-3-4
  .generic-form.gray-border
    = form_for [ :user, @post ] do |f|
      == render 'form', f: f
      .buttons
        = f.submit '登録'
        = link_to 'キャンセル', :user_posts

app/views/user/posts/show.html.slim
.post-show-wrapper.pure-u-3-4
  .post.gray-border
    .title = @post.title
    .info
      span.user
        = @post.user.family_name
        = @post.user.given_name
        span.label が
        = @post.created_at
        spam.label に質問
    .content
      = markdown @post.content

  .answers.gray-border
    - @post.answers.each do |answer|      
      .info
        span.user
          = answer.user.family_name
          = answer.user.given_name
          span.label が
          = @post.created_at
          spam.label に回答
      .content
        = markdown answer.content
    - if @post.answers.empty?
      span 回答がありません。
  
  .generic-form.gray-border
    = form_for(@answer, url: user_post_answer_index_path(post_id: @post.id)) do |f|
      == render 'user/posts/answer', f: f
      .buttons
        = f.submit '登録'

app/views/user/shared/_header.html.slim
header
  = link_to 'PETRI', :user_root, class: 'logo-mark'
  = content_tag(:span, flash.notice, class: 'notice') if flash.notice
  = content_tag(:span, flash.alert, class: 'alert') if flash.alert
  - if current_user
    = link_to 'ログアウト', :user_session, method: :delete
    span.login-status さん
    span.login-status = current_user.given_name
    span.login-status ようこそ、
  - else
    = link_to 'ログイン', :new_user_session
#top-menu

app/views/user/top/index.html.slim
- @title = 'トップページ'
h1 = @title
ul.menu
  li
    = link_to '質問一覧', :user_posts
  li
    = link_to '新規質問', :new_user_post